api_version = "2025-10"

[[extensions]]
uid = "3e0cf115-e650-c61b-761c-5cc2e7a2c4a24ed81c33"
type = "ui_extension"
name = "Product Order Block"
handle = "product-order-block"

  [[extensions.targeting]]
  module = "./src/BlockExtension.tsx"
  target = "admin.product-details.block.render"

[[extensions]]
type = "ui_extension"
name = "Product Order Action"
handle = "product-order-action"
uid = "b9867cbf-d901-7bd7-d5d9-ed0ac356c09f5b3b901a"

  [[extensions.targeting]]
  module = "./src/ActionExtension.tsx"
  target = "admin.product-details.action.render"
