# This file stores configurations for your Shopify app.
name = "Product Demand"
client_id = "96e96c6bb0e33380b852c0df2d0fd82b"
application_url = "https://product-demand-production.up.railway.app"
embedded = true

[auth]
redirect_urls = [
  "https://product-demand-production.up.railway.app/auth/callback",
  "https://product-demand-production.up.railway.app/auth/shopify/callback",
  "https://product-demand-production.up.railway.app/api/auth/callback"
]

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations,read_orders,read_reports"

[webhooks]
api_version = "2025-10"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
