CREATE TABLE "VisionBoard" (
  "id" SERIAL NOT NULL,
  "name" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "VisionBoard_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "VisionBoardItem" (
  "id" SERIAL NOT NULL,
  "boardId" INTEGER NOT NULL,
  "type" TEXT NOT NULL DEFAULT 'image',
  "imageData" TEXT,
  "content" TEXT,
  "x" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "y" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "width" DOUBLE PRECISION NOT NULL DEFAULT 200,
  "height" DOUBLE PRECISION NOT NULL DEFAULT 200,
  "zIndex" INTEGER NOT NULL DEFAULT 0,
  "title" TEXT,
  "notes" TEXT,
  "fields" JSONB NOT NULL DEFAULT '[]',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "VisionBoardItem_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "VisionBoardItem" ADD CONSTRAINT "VisionBoardItem_boardId_fkey"
  FOREIGN KEY ("boardId") REFERENCES "VisionBoard"("id") ON DELETE CASCADE ON UPDATE CASCADE;
